var UP_PRESS = 0,
    LEFT_PRESS = 1,
    DOWN_PRESS = 2,
    RIGHT_PRESS = 3,
    UP_RELEASE = 4,
    LEFT_RELEASE = 5,
    DOWN_RELEASE = 6,
    RIGHT_RELEASE = 7,
    RUN_RIGHT = 8,
    RUN_LEFT = 9,
    RUN_UP = 10,
    RUN_DOWN = 11,
    STOP_X = 12,
    STOP_Y = 13,
    HIT = 14;
    SLASH = 15;
var FRAMERATE = 150; // milliseconds per frame
var SCALE = 0.5;
var WALKMASK_SCALE = 1;