lava.frames = [
  [//frame0---------------------
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                       ##".split(""),
  "#                        ".split(""),
  "                         ".split(""),
  "   ##                    ".split(""),
  "    ##                   ".split(""),
  "     ##                  ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  ],

  [//frame1-------
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  " #                      #".split(""),
  " ##                      ".split(""),
  " #                       ".split(""),
  "     ##                  ".split(""),
  "      ##                 ".split(""),
  "       ##                ".split(""),
  "                         ".split(""),
  ],

  [//frame2
  "   ##                    ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "    #                    ".split(""),
  "   ###                   ".split(""),
  "    #                    ".split(""),
  "       ##                ".split(""),
  "        ##               ".split(""),
  "         ##              ".split(""),
  ],

  [//frame3
  "     ##                  ".split(""),
  "     ##                  ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "      #                  ".split(""),
  "     ###                 ".split(""),
  "      #                  ".split(""),
  "        ##               ".split(""),
  "         ##              ".split(""),
  ],

  [//frame4
  "                         ".split(""),
  "       ##                ".split(""),
  "       ##                ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "        #                ".split(""),
  "       ###               ".split(""),
  "        #                ".split(""),
  "          ##             ".split(""),
  ],

  [//frame5
  "                         ".split(""),
  "                         ".split(""),
  "         ##              ".split(""),
  "         ##              ".split(""),
  "#                        ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "          #              ".split(""),
  "         ###             ".split(""),
  "          #              ".split(""),
  ],

  [//frame6
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "           ##            ".split(""),
  "           ##            ".split(""),
  " ##                      ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "            #            ".split(""),
  "           ###           ".split(""),
  ],

  [//frame7
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "             ##          ".split(""),
  "             ##          ".split(""),
  "   ##                    ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "             #           ".split(""),
  ],

  [//frame8
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "               ##        ".split(""),
  "               ##        ".split(""),
  "     ##                  ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  ],

  [//frame9
  "             ##          ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                 ##      ".split(""),
  "                 ##      ".split(""),
  "       ##                ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  ],

  [//frame10
  "                         ".split(""),
  "               ##        ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                   ##    ".split(""),
  "                   ##    ".split(""),
  "         ##              ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  ],

  [//frame11
  "                         ".split(""),
  "                         ".split(""),
  "                 ##      ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "#                        ".split(""),
  "                     ##  ".split(""),
  "                     ##  ".split(""),
  "           ##            ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  ],

  [//frame12
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                   ##    ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "#                        ".split(""),
  "##                       ".split(""),
  " ##                      ".split(""),
  "                       ##".split(""),
  "                       ##".split(""),
  "             ##          ".split(""),
  "                         ".split(""),
  ],

  [//frame13
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  "                     ##  ".split(""),
  "                         ".split(""),
  "                         ".split(""),
  " ##                      ".split(""),
  "  ##                     ".split(""),
  "   ##                    ".split(""),
  "                        #".split(""),
  "                        #".split(""),
  "               ##        ".split(""),
  ]
],